version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user1:user1user1@rc1b-4eda1icabiykf6y5.mdb.yandexcloud.net:6432/github_parser
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
